import type { DashboardSnapshot } from './types';

export const mockDashboardSnapshot: DashboardSnapshot = {
  status: {
    status: 'ok',
    version: 'KAIROS Gateway v1.0.0',
    timestamp: Date.now(),
    entropy: {
      initialized: true,
      source: 'ESP32 QRNG',
      source_type: 'hardware',
      available_bytes: 18432,
      total_generated: 2147483648,
      pool_size: 4096,
      hardware_available: true,
      openssl_available: true,
    },
    server: {
      running: true,
      port: 8080,
      active_connections: 14,
      total_requests: 23784,
    },
  },
  threatHistory: [
    { time: '00:00', score: 0.12, events: 3 },
    { time: '00:05', score: 0.18, events: 4 },
    { time: '00:10', score: 0.26, events: 8 },
    { time: '00:15', score: 0.41, events: 11 },
    { time: '00:20', score: 0.59, events: 13 },
    { time: '00:25', score: 0.72, events: 18 },
    { time: '00:30', score: 0.66, events: 14 },
    { time: '00:35', score: 0.78, events: 20 },
    { time: '00:40', score: 0.58, events: 15 },
    { time: '00:45', score: 0.46, events: 9 },
  ],
  events: [
    {
      id: 'evt-1',
      type: 'anomaly',
      level: 'orange',
      source: 'relay-12',
      target: 'gateway-core',
      score: 0.74,
      confidence: 0.88,
      timestamp: '2026-09-19T20:12:09Z',
      description: 'Burst traffic pattern matched suspicious beaconing profile.',
    },
    {
      id: 'evt-2',
      type: 'port-scan',
      level: 'red',
      source: '10.18.3.44',
      target: 'base-station-02',
      score: 0.91,
      confidence: 0.96,
      timestamp: '2026-09-19T20:10:42Z',
      description: 'External host probed 43 distinct ports over 18 seconds.',
    },
    {
      id: 'evt-3',
      type: 'rate-limit',
      level: 'yellow',
      source: 'device-03',
      target: 'gateway',
      score: 0.52,
      confidence: 0.71,
      timestamp: '2026-09-19T20:08:27Z',
      description: 'Session reached threshold for repeated authentication failures.',
    },
  ],
  sessions: [
    { sessionId: 'sess-01', device: 'Drone-ALPHA', region: 'north-east', status: 'active', keyAge: 84, threatScore: 0.42, bytes: 412000 },
    { sessionId: 'sess-02', device: 'Relay-12', region: 'edge-net', status: 'isolated', keyAge: 11, threatScore: 0.76, bytes: 236000 },
    { sessionId: 'sess-03', device: 'Base-Station-4', region: 'central', status: 'rotating', keyAge: 48, threatScore: 0.61, bytes: 708000 },
    { sessionId: 'sess-04', device: 'Field-Unit-9', region: 'west', status: 'blocked', keyAge: 2, threatScore: 0.94, bytes: 133000 },
  ],
  devices: [
    { id: 'device-01', name: 'ESP32 QRNG', status: 'online', entropy: 98, latency: 21, risk: 0.18 },
    { id: 'device-02', name: 'Drone-ALPHA', status: 'warning', entropy: 81, latency: 44, risk: 0.64 },
    { id: 'device-03', name: 'Relay-12', status: 'online', entropy: 86, latency: 33, risk: 0.42 },
    { id: 'device-04', name: 'Base-Station-2', status: 'offline', entropy: 0, latency: 0, risk: 0.92 },
  ],
  actions: [
    { id: 'act-1', type: 'rotate_key', target: 'sess-02', severity: 'high', status: 'complete', summary: 'Session key rotated after orange-level anomaly threshold crossing.' },
    { id: 'act-2', type: 'rate_limit', target: '10.18.3.44', severity: 'critical', status: 'executing', summary: 'Ingress limiter raised for red-level port scan activity.' },
    { id: 'act-3', type: 'alert_admin', target: 'security-ops', severity: 'medium', status: 'queued', summary: 'Operator alert queued for anomalous relay mesh traffic.' },
  ],
  topology: [
    { id: 'gateway', x: 48, y: 40, label: 'Gateway', type: 'gateway' },
    { id: 'ml', x: 20, y: 24, label: 'ML', type: 'ml' },
    { id: 'policy', x: 74, y: 24, label: 'DTRE', type: 'policy' },
    { id: 'sensor', x: 18, y: 70, label: 'QRNG', type: 'sensor' },
    { id: 'device', x: 78, y: 70, label: 'Network', type: 'device' },
  ],
  connections: [
    { from: 'sensor', to: 'gateway', strength: 0.9 },
    { from: 'gateway', to: 'ml', strength: 0.7 },
    { from: 'gateway', to: 'policy', strength: 0.8 },
    { from: 'policy', to: 'device', strength: 0.7 },
    { from: 'gateway', to: 'device', strength: 0.6 },
  ],
};
